import { 
  User, 
  Module, 
  TeacherAssignment, 
  StudentEnrollment, 
  Question, 
  Assessment, 
  Submission 
} from "./types";

// Users
export const users: User[] = [
  {
    id: "1",
    firstName: "Admin",
    lastName: "User",
    email: "admin@university.edu",
    name: "Admin User",
    role: "admin",
    status: "active",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@university.edu",
    name: "Dr. John Doe",
    role: "teacher",
    status: "active",
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "3",
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@university.edu",
    name: "Prof. Jane Smith",
    role: "teacher",
    status: "active",
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "4",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@student.edu",
    name: "Alice Johnson",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "5",
    firstName: "Bob",
    lastName: "Williams",
    email: "bob.williams@student.edu",
    name: "Bob Williams",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "6",
    firstName: "Carol",
    lastName: "Davis",
    email: "carol.davis@student.edu",
    name: "Carol Davis",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "7",
    firstName: "David",
    lastName: "Miller",
    email: "david.miller@student.edu",
    name: "David Miller",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "8",
    firstName: "Emma",
    lastName: "Brown",
    email: "emma.brown@student.edu",
    name: "Emma Brown",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
  {
    id: "9",
    firstName: "Frank",
    lastName: "Wilson",
    email: "frank.wilson@student.edu",
    name: "Frank Wilson",
    role: "student",
    status: "active",
    createdAt: "2024-09-01T10:00:00Z",
  },
];

// Modules
export const modules: Module[] = [
  {
    id: "m1",
    code: "CS101",
    name: "Introduction to Programming",
    description: "Fundamentals of programming using Python",
    topics: [
      { id: "t1", name: "Variables and Data Types", moduleId: "m1" },
      { id: "t2", name: "Control Structures", moduleId: "m1" },
      { id: "t3", name: "Functions", moduleId: "m1" },
      { id: "t4", name: "Object-Oriented Programming", moduleId: "m1" },
    ],
  },
  {
    id: "m2",
    code: "CS201",
    name: "Data Structures and Algorithms",
    description: "Core data structures and algorithmic techniques",
    topics: [
      { id: "t5", name: "Arrays and Lists", moduleId: "m2" },
      { id: "t6", name: "Trees and Graphs", moduleId: "m2" },
      { id: "t7", name: "Sorting Algorithms", moduleId: "m2" },
      { id: "t8", name: "Dynamic Programming", moduleId: "m2" },
    ],
  },
  {
    id: "m3",
    code: "CS301",
    name: "Database Systems",
    description: "Relational databases and SQL",
    topics: [
      { id: "t9", name: "Relational Model", moduleId: "m3" },
      { id: "t10", name: "SQL Queries", moduleId: "m3" },
      { id: "t11", name: "Normalization", moduleId: "m3" },
      { id: "t12", name: "Transactions", moduleId: "m3" },
    ],
  },
];

// Teacher Assignments
export const teacherAssignments: TeacherAssignment[] = [
  {
    id: "ta1",
    teacherId: "2",
    moduleId: "m1",
    teachingRole: "Lecturer",
  },
  {
    id: "ta2",
    teacherId: "3",
    moduleId: "m1",
    teachingRole: "Lab Instructor",
  },
  {
    id: "ta3",
    teacherId: "2",
    moduleId: "m2",
    teachingRole: "Lecturer",
  },
  {
    id: "ta4",
    teacherId: "3",
    moduleId: "m3",
    teachingRole: "Lecturer",
  },
];

// Student Enrollments
export const studentEnrollments: StudentEnrollment[] = [
  { id: "e1", studentId: "4", moduleId: "m1", group: "A" },
  { id: "e2", studentId: "4", moduleId: "m2", group: "A" },
  { id: "e3", studentId: "5", moduleId: "m1", group: "B" },
  { id: "e4", studentId: "5", moduleId: "m3", group: "A" },
  { id: "e5", studentId: "6", moduleId: "m1", group: "A" },
  { id: "e6", studentId: "6", moduleId: "m2", group: "B" },
  { id: "e7", studentId: "7", moduleId: "m1", group: "A" },
  { id: "e8", studentId: "8", moduleId: "m1", group: "B" },
  { id: "e9", studentId: "9", moduleId: "m1", group: "A" },
];

// Questions
export const questions: Question[] = [
  {
    id: "q1",
    moduleId: "m1",
    topicId: "t1",
    type: "MCQ",
    text: "Which of the following is NOT a valid Python data type?",
    points: 2,
    options: ["int", "float", "char", "str"],
    correctAnswer: "char",
    createdBy: "2",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "q2",
    moduleId: "m1",
    topicId: "t2",
    type: "True/False",
    text: "Python uses curly braces {} to define code blocks.",
    points: 1,
    options: ["True", "False"],
    correctAnswer: "False",
    createdBy: "2",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "q3",
    moduleId: "m1",
    topicId: "t3",
    type: "Descriptive",
    text: "Explain the difference between parameters and arguments in Python functions.",
    points: 5,
    referenceAnswer: "Parameters are the variables listed in the function definition, while arguments are the actual values passed to the function when it is called. Parameters act as placeholders that define what type of data the function expects, whereas arguments are the concrete data provided during function invocation.",
    keywords: [
      { text: "parameters", weight: 1 },
      { text: "function definition", weight: 1 },
      { text: "arguments", weight: 1 },
      { text: "values passed", weight: 1 },
      { text: "function call", weight: 1 },
    ],
    createdBy: "2",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "q4",
    moduleId: "m1",
    topicId: "t4",
    type: "MCQ",
    text: "Which keyword is used to create a class in Python?",
    points: 2,
    options: ["class", "Class", "define", "def"],
    correctAnswer: "class",
    createdBy: "2",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "q5",
    moduleId: "m2",
    topicId: "t7",
    type: "Descriptive",
    text: "Describe the Quick Sort algorithm and its time complexity.",
    points: 10,
    referenceAnswer: "Quick Sort is a divide-and-conquer sorting algorithm that works by selecting a pivot element and partitioning the array around it. Elements smaller than the pivot go to the left, and larger elements go to the right. This process is recursively applied to the sub-arrays. The average time complexity is O(n log n), but the worst-case time complexity is O(n²) when the pivot is consistently the smallest or largest element.",
    keywords: [
      { text: "divide-and-conquer", weight: 2 },
      { text: "pivot", weight: 2 },
      { text: "partitioning", weight: 2 },
      { text: "O(n log n)", weight: 2 },
      { text: "worst-case", weight: 1 },
      { text: "O(n²)", weight: 1 },
    ],
    createdBy: "2",
    createdAt: "2024-01-25T10:00:00Z",
  },
];

// Assessments
export const assessments: Assessment[] = [
  {
    id: "a1",
    title: "Python Basics Quiz",
    moduleId: "m1",
    duration: 30,
    startTime: "2026-02-25T10:00:00Z",
    endTime: "2026-02-25T12:00:00Z",
    status: "Scheduled",
    questions: ["q1", "q2", "q3"],
    randomize: false,
    instructions: "This quiz covers basic Python concepts including data types, control structures, and functions.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: true,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-02-15T10:00:00Z",
  },
  {
    id: "a2",
    title: "OOP Concepts Assessment",
    moduleId: "m1",
    duration: 45,
    startTime: "2026-02-20T09:00:00Z",
    endTime: "2026-02-20T11:00:00Z",
    status: "Published",
    questions: ["q4"],
    randomize: false,
    instructions: "Assessment on core OOP concepts such as classes and objects.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: false,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: false,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: false,
    },
    createdBy: "2",
    createdAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "a3",
    title: "Sorting Algorithms Exam",
    moduleId: "m2",
    duration: 60,
    startTime: "2026-02-23T14:00:00Z",
    endTime: "2026-02-23T16:00:00Z",
    status: "Active",
    questions: ["q5"],
    randomize: false,
    instructions: "Exam focused on sorting algorithms with an emphasis on Quick Sort.",
    shuffleAnswers: false,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: true,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-02-18T10:00:00Z",
  },
  {
    id: "a4",
    title: "Midterm Exam - Data Structures",
    moduleId: "m2",
    duration: 120,
    startTime: "2026-03-15T09:00:00Z",
    endTime: "2026-03-15T13:00:00Z",
    status: "Draft",
    questions: [],
    randomize: true,
    instructions: "Midterm exam covering multiple data structure topics.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: false,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: false,
      showTeacherFeedback: false,
      showAiKeywordAnalysis: false,
      showPerQuestionDetails: false,
      showScore: true,
      showQuestionBreakdown: false,
      showKeywordAnalysis: false,
    },
    createdBy: "2",
    createdAt: "2024-02-22T10:00:00Z",
  },
  {
    id: "a5",
    title: "Python Mastery Mixed Outcomes",
    moduleId: "m1",
    duration: 40,
    startTime: "2026-02-26T08:00:00Z",
    endTime: "2026-02-26T10:00:00Z",
    status: "Published",
    questions: ["q1", "q2", "q3"],
    randomize: false,
    instructions: "Comprehensive mixed-level test for analytics and results review.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: true,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-02-26T10:00:00Z",
  },
  {
    id: "a6",
    title: "Result Visibility Case - Hidden Final Score",
    moduleId: "m1",
    duration: 20,
    startTime: "2026-02-27T08:00:00Z",
    endTime: "2026-02-27T09:00:00Z",
    status: "Published",
    questions: ["q3"],
    randomize: false,
    instructions: "Used to validate hidden final score behavior.",
    shuffleAnswers: false,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: false,
    resultsVisibility: {
      showFinalScore: false,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: false,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-02-27T10:00:00Z",
  },
  {
    id: "a7",
    title: "Result Visibility Case - Hidden Breakdown",
    moduleId: "m1",
    duration: 25,
    startTime: "2026-02-28T08:00:00Z",
    endTime: "2026-02-28T09:00:00Z",
    status: "Published",
    questions: ["q3", "q4"],
    randomize: false,
    instructions: "Used to validate hidden score breakdown and per-question details.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: false,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: false,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: false,
      showScore: true,
      showQuestionBreakdown: false,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-02-28T10:00:00Z",
  },
  {
    id: "a8",
    title: "Result Visibility Case - Hidden Feedback",
    moduleId: "m2",
    duration: 30,
    startTime: "2026-03-01T08:00:00Z",
    endTime: "2026-03-01T09:00:00Z",
    status: "Published",
    questions: ["q5"],
    randomize: false,
    instructions: "Used to validate teacher feedback visibility toggle.",
    shuffleAnswers: false,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: true,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: false,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-03-01T10:00:00Z",
  },
  {
    id: "a9",
    title: "Result Visibility Case - Hidden AI Analysis",
    moduleId: "m2",
    duration: 30,
    startTime: "2026-03-02T08:00:00Z",
    endTime: "2026-03-02T09:00:00Z",
    status: "Published",
    questions: ["q5"],
    randomize: false,
    instructions: "Used to validate AI keyword analysis visibility toggle.",
    shuffleAnswers: false,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: true,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: false,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: false,
    },
    createdBy: "2",
    createdAt: "2024-03-02T10:00:00Z",
  },
  {
    id: "a10",
    title: "Live Practice Assessment",
    moduleId: "m1",
    duration: 20,
    startTime: "2026-03-10T08:00:00Z",
    endTime: "2026-03-10T10:00:00Z",
    status: "Active",
    questions: ["q1", "q2"],
    randomize: false,
    instructions: "Active assessment to test Start button flow from dashboard.",
    shuffleAnswers: true,
    autoSubmitOnTimeout: true,
    tabSwitchWarning: false,
    resultsVisibility: {
      showFinalScore: true,
      showScoreBreakdown: true,
      showTeacherFeedback: true,
      showAiKeywordAnalysis: true,
      showPerQuestionDetails: true,
      showScore: true,
      showQuestionBreakdown: true,
      showKeywordAnalysis: true,
    },
    createdBy: "2",
    createdAt: "2024-03-03T10:00:00Z",
  },
];

// Submissions
export const submissions: Submission[] = [
  {
    id: "s1",
    assessmentId: "a2",
    studentId: "4",
    answers: [
      {
        questionId: "q4",
        answer: "class",
      },
    ],
    status: "Graded",
    score: 2,
    maxScore: 2,
    submittedAt: "2026-02-20T09:35:00Z",
    gradedAt: "2026-02-20T10:00:00Z",
    feedback: "Perfect! Well done.",
  },
  {
    id: "s2",
    assessmentId: "a2",
    studentId: "5",
    answers: [
      {
        questionId: "q4",
        answer: "Class",
      },
    ],
    status: "Graded",
    score: 0,
    maxScore: 2,
    submittedAt: "2026-02-20T09:40:00Z",
    gradedAt: "2026-02-20T10:05:00Z",
    feedback: "Remember that Python is case-sensitive.",
  },
  {
    id: "s3",
    assessmentId: "a3",
    studentId: "4",
    answers: [
      {
        questionId: "q5",
        answer: "Quick Sort uses a pivot element to divide the array into smaller parts. Elements are compared with the pivot and sorted accordingly. The time complexity is usually O(n log n) but can be O(n²) in worst cases when the pivot selection is poor.",
        detectedKeywords: ["pivot", "O(n log n)", "worst-case", "O(n²)"],
        missingKeywords: ["divide-and-conquer", "partitioning"],
        autoScore: 6,
      },
    ],
    status: "Submitted",
    maxScore: 10,
    submittedAt: "2026-02-23T14:55:00Z",
  },
  {
    id: "s4",
    assessmentId: "a3",
    studentId: "6",
    answers: [
      {
        questionId: "q5",
        answer: "",
      },
    ],
    status: "In Progress",
    maxScore: 10,
  },
  {
    id: "s5",
    assessmentId: "a5",
    studentId: "4",
    answers: [
      { questionId: "q1", answer: "int" },
      { questionId: "q2", answer: "True" },
      {
        questionId: "q3",
        answer: "Parameters and arguments are related but not the same.",
        detectedKeywords: ["parameters"],
        missingKeywords: ["function definition", "arguments", "values passed", "function call"],
        autoScore: 0,
      },
    ],
    status: "Graded",
    score: 0,
    maxScore: 8,
    submittedAt: "2026-02-26T08:30:00Z",
    gradedAt: "2026-02-26T09:00:00Z",
    feedback: "Needs review of core concepts.",
  },
  {
    id: "s6",
    assessmentId: "a5",
    studentId: "5",
    answers: [
      { questionId: "q1", answer: "char" },
      { questionId: "q2", answer: "True" },
      { questionId: "q3", answer: "Not sure", autoScore: 0 },
    ],
    status: "Graded",
    score: 2,
    maxScore: 8,
    submittedAt: "2026-02-26T08:35:00Z",
    gradedAt: "2026-02-26T09:05:00Z",
    feedback: "Good start. Work on conceptual precision.",
  },
  {
    id: "s7",
    assessmentId: "a5",
    studentId: "6",
    answers: [
      { questionId: "q1", answer: "char" },
      { questionId: "q2", answer: "False" },
      { questionId: "q3", answer: "Short explanation", autoScore: 0 },
    ],
    status: "Graded",
    score: 3,
    maxScore: 8,
    submittedAt: "2026-02-26T08:40:00Z",
    gradedAt: "2026-02-26T09:10:00Z",
    feedback: "Decent objective performance.",
  },
  {
    id: "s8",
    assessmentId: "a5",
    studentId: "7",
    answers: [
      { questionId: "q1", answer: "char" },
      { questionId: "q2", answer: "False" },
      { questionId: "q3", answer: "Basic explanation", autoScore: 1 },
    ],
    status: "Graded",
    score: 4,
    maxScore: 8,
    submittedAt: "2026-02-26T08:42:00Z",
    gradedAt: "2026-02-26T09:12:00Z",
    feedback: "Average understanding.",
  },
  {
    id: "s9",
    assessmentId: "a5",
    studentId: "8",
    answers: [
      { questionId: "q1", answer: "char" },
      { questionId: "q2", answer: "False" },
      { questionId: "q3", answer: "Partially complete", autoScore: 2 },
    ],
    status: "Graded",
    score: 5,
    maxScore: 8,
    submittedAt: "2026-02-26T08:45:00Z",
    gradedAt: "2026-02-26T09:15:00Z",
    feedback: "Good objective section.",
  },
  {
    id: "s10",
    assessmentId: "a5",
    studentId: "9",
    answers: [
      { questionId: "q1", answer: "char" },
      { questionId: "q2", answer: "True" },
      {
        questionId: "q3",
        answer: "Parameters are declared in function definitions while arguments are actual values supplied at call time.",
        detectedKeywords: ["parameters", "function definition", "arguments", "values passed", "function call"],
        missingKeywords: [],
        autoScore: 5,
      },
    ],
    status: "Graded",
    score: 7,
    maxScore: 8,
    submittedAt: "2026-02-26T08:50:00Z",
    gradedAt: "2026-02-26T09:20:00Z",
    feedback: "Excellent descriptive response.",
  },
  {
    id: "s11",
    assessmentId: "a6",
    studentId: "4",
    answers: [
      {
        questionId: "q3",
        answer: "Parameters are in the function definition, arguments are passed at invocation.",
        detectedKeywords: ["parameters", "function definition", "arguments"],
        missingKeywords: ["values passed", "function call"],
        autoScore: 3,
      },
    ],
    status: "Graded",
    score: 3,
    maxScore: 5,
    submittedAt: "2026-02-27T08:20:00Z",
    gradedAt: "2026-02-27T08:40:00Z",
    feedback: "Good answer with minor omissions.",
  },
  {
    id: "s12",
    assessmentId: "a7",
    studentId: "4",
    answers: [
      {
        questionId: "q3",
        answer: "Parameters define expected input and arguments provide actual values.",
        detectedKeywords: ["parameters", "arguments"],
        missingKeywords: ["function definition", "values passed", "function call"],
        autoScore: 2,
      },
      {
        questionId: "q4",
        answer: "class",
      },
    ],
    status: "Graded",
    score: 4,
    maxScore: 7,
    submittedAt: "2026-02-28T08:25:00Z",
    gradedAt: "2026-02-28T08:45:00Z",
    feedback: "Good objective result.",
  },
  {
    id: "s13",
    assessmentId: "a8",
    studentId: "4",
    answers: [
      {
        questionId: "q5",
        answer: "Quick sort uses divide-and-conquer and partitioning with a pivot. Typical complexity is O(n log n), worst case O(n^2).",
        detectedKeywords: ["divide-and-conquer", "pivot", "partitioning", "O(n log n)", "worst-case", "O(n²)"],
        missingKeywords: [],
        autoScore: 10,
      },
    ],
    status: "Graded",
    score: 10,
    maxScore: 10,
    submittedAt: "2026-03-01T08:25:00Z",
    gradedAt: "2026-03-01T08:55:00Z",
    feedback: "Outstanding explanation.",
  },
  {
    id: "s14",
    assessmentId: "a9",
    studentId: "4",
    answers: [
      {
        questionId: "q5",
        answer: "Quick sort partitions elements around a pivot and recursively sorts partitions.",
        detectedKeywords: ["pivot", "partitioning"],
        missingKeywords: ["divide-and-conquer", "O(n log n)", "worst-case", "O(n²)"],
        autoScore: 5,
      },
    ],
    status: "Graded",
    score: 5,
    maxScore: 10,
    submittedAt: "2026-03-02T08:30:00Z",
    gradedAt: "2026-03-02T09:00:00Z",
    feedback: "Fair response; include complexity details.",
  },
];

// Current logged in user (for demo purposes)
export let currentUser: User = users[0]; // Default to admin

export function setCurrentUser(user: User) {
  currentUser = user;
}

export function getCurrentUser() {
  return currentUser;
}
